name: Run Cypress Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # services:
    #   sorry-cypress:
    #     image: agoldis/sorry-cypress-director
    #     ports:
    #       - 8080:8080

    steps:
      - name: Install Dependencies
        run:  echo ${ls -a}

      - name: Check .env.example file
        run: |
          if [ ! -f ./.env.example ]; then
            echo ".env.example file not found!"
            exit 1
          fi
          
      - name: Install Dependencies
        run: echo $(cat ./.env.example) PRIVATE_KEY = ${{ secrets.privateKey }} PUBLIC_KEY = ${{ secrets.publicKey }} >> .env

      - name: Start the server
        run: cat .env