name: Run Cypress Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: privateKey
    # services:
    #   sorry-cypress:
    #     image: agoldis/sorry-cypress-director
    #     ports:
    #       - 8080:8080

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run:  echo $(ls -a)

      - name: Install Dependencies
        run: |
          echo "$(cat ./.env.example)" > .env
          echo "PRIVATE_KEY=${{ secrets.privateKey }}" >> .env
          echo "PUBLIC_KEY=${{ secrets.publicKey }}" >> .env

      - name: Start the server
        run: node index.js

      - name: Start the server
        run: cat .env