name: Run Cypress Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: privateKey
    # services:TEST
    #   sorry-cypress:
    #     image: agoldis/sorry-cypress-director
    #     ports:
    #       - 8080:8080

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          echo $(cat .env.example) > .env

      - name: Start the server
        run: yarn

      - name: Start the server
        run: yarn

      - name: Start the server
        run: node index.js

      - name: Start the server
        run: cat .env